// <auto-generated />
using System;
using ExportOrderDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExportOrderWebServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231108224230_09-11_CustomsLetter")]
    partial class _0911_CustomsLetter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocumentEntityExportOrderEntity", b =>
                {
                    b.Property<long>("DocumentsId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExportOrdersId")
                        .HasColumnType("bigint");

                    b.HasKey("DocumentsId", "ExportOrdersId");

                    b.HasIndex("ExportOrdersId");

                    b.ToTable("ExportOrders_Documents", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CarrierCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BlTemplate")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("LocationId");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CarrierTerminalDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentPOL")
                        .HasColumnType("text");

                    b.Property<long>("CarrierId")
                        .HasColumnType("bigint");

                    b.Property<string>("Contract")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateContract")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TerminalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.ToTable("CarrierDetails");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CountryCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("ENG")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RUS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CustomsCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("Dapartment")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Office")
                        .HasColumnType("text");

                    b.Property<string>("OfficeShort")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("CustomsOffices");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.LocationCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<string>("UnLocode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreateUserId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.TerminalCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<long?>("CustomsId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("CustomsId");

                    b.HasIndex("LocationId");

                    b.ToTable("Terminals");
                });

            modelBuilder.Entity("ExportOrderEntites.Cntr.CntrTpSz", b =>
                {
                    b.Property<string>("ISO")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Normolize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ISO");

                    b.ToTable("ContainerTypeSize");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.CommodityCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("HSCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("IMO")
                        .HasColumnType("text");

                    b.Property<bool>("IsIMO")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UNNO")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("Commodities");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.CustomerCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreateUserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.DocumentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Consignee")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ContarctNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shipper")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.DocumentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommodityEngName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommodityHSCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CommodityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<double?>("GrossWt")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.Property<string>("IMO")
                        .HasColumnType("text");

                    b.Property<bool>("IsIMO")
                        .HasColumnType("boolean");

                    b.Property<double?>("NetWt")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<string>("UNNO")
                        .HasColumnType("text");

                    b.Property<double?>("Volume")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentRecord");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ContainerContent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DocumentRecordId")
                        .HasColumnType("integer");

                    b.Property<long>("ExportOrderRecordId")
                        .HasColumnType("bigint");

                    b.Property<double?>("GrossWt")
                        .HasColumnType("double precision");

                    b.Property<double?>("NetWt")
                        .HasColumnType("double precision");

                    b.Property<string>("PackageName")
                        .HasColumnType("text");

                    b.Property<long?>("PackageQty")
                        .HasColumnType("bigint");

                    b.Property<double?>("Volume")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DocumentRecordId");

                    b.HasIndex("ExportOrderRecordId");

                    b.ToTable("ContainerContent");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CarrierId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Dated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Num")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long?>("VesselCallDetailId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("PersonId");

                    b.HasIndex("VesselCallDetailId");

                    b.ToTable("ExportOrders");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CntrNum")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<double>("CntrTareWt")
                        .HasColumnType("double precision");

                    b.Property<string>("CntrTypeISO")
                        .HasColumnType("character varying(4)");

                    b.Property<long>("ExportOrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Seal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CntrTypeISO");

                    b.HasIndex("ExportOrderId");

                    b.ToTable("ExportOrder_Records", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.MyCompany.MyCompanyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("MyCompany");
                });

            modelBuilder.Entity("ExportOrderEntites.MyCompany.PersonEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("text");

                    b.Property<string>("BirthYear")
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("FamilyName")
                        .HasColumnType("text");

                    b.Property<long?>("MyCompanyEntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Passport")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("SurName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("MyCompanyEntityId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselCallDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentPOD")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<long?>("PODId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long>("VesselCallId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("PODId");

                    b.HasIndex("VesselCallId");

                    b.ToTable("VesselCall_Details", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselCallEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ETA")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ETS")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TerminalId")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long>("VesselId")
                        .HasColumnType("bigint");

                    b.Property<string>("VoyageNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoyageNoTerminal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("TerminalId");

                    b.HasIndex("VesselId");

                    b.ToTable("VesselCalls");
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CaptainFamily")
                        .HasColumnType("text");

                    b.Property<string>("CaptainName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("FlagId")
                        .HasColumnType("bigint");

                    b.Property<string>("IMO")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TerminalCode")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("FlagId");

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DocumentEntityExportOrderEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.Document.DocumentEntity", null)
                        .WithMany()
                        .HasForeignKey("DocumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExportOrderEntites.ExportOrder.ExportOrderEntity", null)
                        .WithMany()
                        .HasForeignKey("ExportOrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CarrierCatalog", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.HasOne("ExportOrderEntites.Catalog.LocationCatalog", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("CreateUser");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CarrierTerminalDetails", b =>
                {
                    b.HasOne("ExportOrderEntites.Catalog.CarrierCatalog", "Carrier")
                        .WithMany("CarrierDetails")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CountryCatalog", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CustomsCatalog", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.LocationCatalog", b =>
                {
                    b.HasOne("ExportOrderEntites.Catalog.CountryCatalog", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("Country");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.TerminalCatalog", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.HasOne("ExportOrderEntites.Catalog.CustomsCatalog", "Customs")
                        .WithMany()
                        .HasForeignKey("CustomsId");

                    b.HasOne("ExportOrderEntites.Catalog.LocationCatalog", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("CreateUser");

                    b.Navigation("Customs");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.CommodityCatalog", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.CustomerCatalog", b =>
                {
                    b.HasOne("ExportOrderEntites.Catalog.CountryCatalog", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("Country");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.DocumentEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.DocumentRecord", b =>
                {
                    b.HasOne("ExportOrderEntites.Document.DocumentEntity", "Document")
                        .WithMany("Records")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ContainerContent", b =>
                {
                    b.HasOne("ExportOrderEntites.Document.DocumentRecord", "DocumentRecord")
                        .WithMany()
                        .HasForeignKey("DocumentRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExportOrderEntites.ExportOrder.ExportOrderRecord", "ExportOrderRecord")
                        .WithMany("Contents")
                        .HasForeignKey("ExportOrderRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentRecord");

                    b.Navigation("ExportOrderRecord");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.Catalog.CarrierCatalog", "Carrier")
                        .WithMany()
                        .HasForeignKey("CarrierId");

                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.HasOne("ExportOrderEntites.MyCompany.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("ExportOrderEntites.VesselCall.VesselCallDetail", "VesselCallDetail")
                        .WithMany("ExportOrders")
                        .HasForeignKey("VesselCallDetailId");

                    b.Navigation("Carrier");

                    b.Navigation("CreateUser");

                    b.Navigation("Person");

                    b.Navigation("VesselCallDetail");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderRecord", b =>
                {
                    b.HasOne("ExportOrderEntites.Cntr.CntrTpSz", "CntrType")
                        .WithMany()
                        .HasForeignKey("CntrTypeISO");

                    b.HasOne("ExportOrderEntites.ExportOrder.ExportOrderEntity", "ExportOrder")
                        .WithMany("Records")
                        .HasForeignKey("ExportOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CntrType");

                    b.Navigation("ExportOrder");
                });

            modelBuilder.Entity("ExportOrderEntites.MyCompany.MyCompanyEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.MyCompany.PersonEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.HasOne("ExportOrderEntites.MyCompany.MyCompanyEntity", null)
                        .WithMany("Persons")
                        .HasForeignKey("MyCompanyEntityId");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselCallDetail", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.HasOne("ExportOrderEntites.Catalog.LocationCatalog", "POD")
                        .WithMany()
                        .HasForeignKey("PODId");

                    b.HasOne("ExportOrderEntites.VesselCall.VesselCallEntity", "VesselCall")
                        .WithMany("Details")
                        .HasForeignKey("VesselCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateUser");

                    b.Navigation("POD");

                    b.Navigation("VesselCall");
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselCallEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.HasOne("ExportOrderEntites.Catalog.TerminalCatalog", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExportOrderEntites.VesselCall.VesselEntity", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateUser");

                    b.Navigation("Terminal");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExportOrderEntites.Catalog.CountryCatalog", "Flag")
                        .WithMany()
                        .HasForeignKey("FlagId");

                    b.Navigation("CreateUser");

                    b.Navigation("Flag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExportOrderEntites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CarrierCatalog", b =>
                {
                    b.Navigation("CarrierDetails");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.DocumentEntity", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderEntity", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderRecord", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("ExportOrderEntites.MyCompany.MyCompanyEntity", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselCallDetail", b =>
                {
                    b.Navigation("ExportOrders");
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselCallEntity", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
