// <auto-generated />
using System;
using System.Collections.Generic;
using ExportOrderDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExportOrderWebServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250616131928_AuditLog_16_06")]
    partial class AuditLog_16_06
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocumentEntityExportOrderEntity", b =>
                {
                    b.Property<long>("DocumentsId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExportOrdersId")
                        .HasColumnType("bigint");

                    b.HasKey("DocumentsId", "ExportOrdersId");

                    b.HasIndex("ExportOrdersId");

                    b.ToTable("ExportOrders_Documents", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.AuditLog.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Dictionary<string, object>>("NewValues")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, object>>("OldValues")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ExportOrderEntites.BillofLading.BillofLadingContainerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BillofLadingEntityId")
                        .HasColumnType("uuid");

                    b.Property<double>("CargoWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("CommodityCode")
                        .HasColumnType("text");

                    b.Property<string>("CommodityGroup")
                        .HasColumnType("text");

                    b.Property<string>("ContainerNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoodsDescription")
                        .HasColumnType("text");

                    b.Property<string>("GoodsDescriptionRu")
                        .HasColumnType("text");

                    b.Property<string>("ImoClass")
                        .HasColumnType("text");

                    b.Property<bool>("IsAlcohol")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsImo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMilitaryCargo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOog")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRef")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSoc")
                        .HasColumnType("boolean");

                    b.Property<long>("LockToken")
                        .HasColumnType("bigint");

                    b.Property<int>("PackageQty")
                        .HasColumnType("integer");

                    b.Property<string>("SealNo")
                        .HasColumnType("text");

                    b.Property<string>("SealOth")
                        .HasColumnType("text");

                    b.Property<string>("SealShr")
                        .HasColumnType("text");

                    b.Property<int>("TareWeight")
                        .HasColumnType("integer");

                    b.Property<int?>("TempSet")
                        .HasColumnType("integer");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Unno")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BillofLadingEntityId");

                    b.ToTable("BillofLading_ContainerRecords", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.BillofLading.BillofLadingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("ConsigneeAddress")
                        .HasColumnType("text");

                    b.Property<string>("ConsigneeAddressRu")
                        .HasColumnType("text");

                    b.Property<string>("ConsigneeCountryRu")
                        .HasColumnType("text");

                    b.Property<string>("ConsigneeName")
                        .HasColumnType("text");

                    b.Property<string>("ConsigneeNameRu")
                        .HasColumnType("text");

                    b.Property<string>("ConsigneeTaxNo")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomsDeliveryMode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("F_POD")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LockToken")
                        .HasColumnType("bigint");

                    b.Property<string>("NotifyAddress")
                        .HasColumnType("text");

                    b.Property<string>("NotifyEmail")
                        .HasColumnType("text");

                    b.Property<string>("NotifyName")
                        .HasColumnType("text");

                    b.Property<string>("Num")
                        .HasColumnType("text");

                    b.Property<string>("POD")
                        .HasColumnType("text");

                    b.Property<string>("POL")
                        .HasColumnType("text");

                    b.Property<string>("POR")
                        .HasColumnType("text");

                    b.Property<string>("ServiceCode")
                        .HasColumnType("text");

                    b.Property<string>("ShipperAddress")
                        .HasColumnType("text");

                    b.Property<string>("ShipperAddressRu")
                        .HasColumnType("text");

                    b.Property<string>("ShipperCountryRu")
                        .HasColumnType("text");

                    b.Property<string>("ShipperName")
                        .HasColumnType("text");

                    b.Property<string>("ShipperNameRu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SobDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TS_PORT")
                        .HasColumnType("text");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long?>("VesselCallDetailId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VesselCallDetailId");

                    b.ToTable("BillofLadings", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CarrierCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BlTemplate")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("LocationId");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CarrierTerminalDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentPOL")
                        .HasColumnType("text");

                    b.Property<long>("CarrierId")
                        .HasColumnType("bigint");

                    b.Property<string>("Contract")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateContract")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TerminalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.ToTable("CarrierDetails");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CountryCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("ENG")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RUS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CustomsCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("Dapartment")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Office")
                        .HasColumnType("text");

                    b.Property<string>("OfficeShort")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("CustomsOffices");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.LocationCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<string>("UnLocode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreateUserId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.SupplementaryUnitCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Code")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("SupplementaryUnits");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.TerminalCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<long?>("CustomsId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("CustomsId");

                    b.HasIndex("LocationId");

                    b.ToTable("Terminals");
                });

            modelBuilder.Entity("ExportOrderEntites.Cntr.CntrTpSz", b =>
                {
                    b.Property<string>("ISO")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Normolize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ISO");

                    b.ToTable("ContainerTypeSize");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.CommodityCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("HSCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("IMO")
                        .HasColumnType("text");

                    b.Property<bool>("IsIMO")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UNNO")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("Commodities");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.CustomerCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreateUserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.DocumentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Consignee")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shipper")
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.DocumentHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConsigneeName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Records")
                        .HasColumnType("jsonb");

                    b.Property<string>("ShipperName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("DocumentHistory");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.DocumentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommodityEngName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommodityHSCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CommodityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<double>("GrossWt")
                        .HasColumnType("double precision");

                    b.Property<string>("IMO")
                        .HasColumnType("text");

                    b.Property<bool>("IsIMO")
                        .HasColumnType("boolean");

                    b.Property<double>("NetWt")
                        .HasColumnType("double precision");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<string>("UNNO")
                        .HasColumnType("text");

                    b.Property<double?>("Volume")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentRecord");
                });

            modelBuilder.Entity("ExportOrderEntites.EmailLogRecords.EmailLogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateReciept")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHandle")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EmailLogRecords", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ContainerContent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DocumentRecordId")
                        .HasColumnType("integer");

                    b.Property<long>("ExportOrderRecordId")
                        .HasColumnType("bigint");

                    b.Property<double?>("GrossWt")
                        .HasColumnType("double precision");

                    b.Property<double?>("NetWt")
                        .HasColumnType("double precision");

                    b.Property<string>("PackageName")
                        .HasColumnType("text");

                    b.Property<long?>("PackageQty")
                        .HasColumnType("bigint");

                    b.Property<long?>("SupplementaryUnitId")
                        .HasColumnType("bigint");

                    b.Property<double?>("SupplementaryUnitQuantity")
                        .HasColumnType("double precision");

                    b.Property<double?>("Volume")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DocumentRecordId");

                    b.HasIndex("ExportOrderRecordId");

                    b.HasIndex("SupplementaryUnitId");

                    b.ToTable("ContainerContent");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CarrierId")
                        .HasColumnType("bigint");

                    b.Property<string>("CommodityShort")
                        .HasColumnType("text");

                    b.Property<string>("CommodityShortEn")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Dated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Num")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long?>("VesselCallDetailId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("PersonId");

                    b.HasIndex("VesselCallDetailId");

                    b.ToTable("ExportOrders");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Carrier")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Dated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documents")
                        .HasColumnType("jsonb");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Num")
                        .HasColumnType("text");

                    b.Property<string>("POD")
                        .HasColumnType("text");

                    b.Property<string>("Person")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VesselName")
                        .HasColumnType("text");

                    b.Property<string>("VoyageNo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("ExportOrderHistory");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CntrNum")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<double>("CntrTareWt")
                        .HasColumnType("double precision");

                    b.Property<string>("CntrTypeISO")
                        .HasColumnType("character varying(4)");

                    b.Property<long>("ExportOrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Seal")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CntrTypeISO");

                    b.HasIndex("ExportOrderId");

                    b.ToTable("ExportOrder_Records", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderRecordHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CntrNum")
                        .HasColumnType("text");

                    b.Property<double>("CntrTareWt")
                        .HasColumnType("double precision");

                    b.Property<string>("CntrType")
                        .HasColumnType("text");

                    b.Property<string>("Contents")
                        .HasColumnType("jsonb");

                    b.Property<long?>("ExportOrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Seal")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExportOrderId");

                    b.ToTable("ExportOrderRecordHistory");
                });

            modelBuilder.Entity("ExportOrderEntites.ImportVesselCall.ImportVesselCallDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentPOD")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<long?>("FinalDestinationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PODId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long>("VesselCallId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("FinalDestinationId");

                    b.HasIndex("PODId");

                    b.HasIndex("VesselCallId");

                    b.ToTable("ImportVesselCall_Details", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.ImportVesselCall.ImportVesselCallEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ETA")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ETS")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TerminalId")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long>("VesselId")
                        .HasColumnType("bigint");

                    b.Property<string>("VoyageNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoyageNoTerminal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("TerminalId");

                    b.HasIndex("VesselId");

                    b.ToTable("ImportVesselCalls");
                });

            modelBuilder.Entity("ExportOrderEntites.MyCompany.MyCompanyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("MyCompany");
                });

            modelBuilder.Entity("ExportOrderEntites.MyCompany.PersonEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("text");

                    b.Property<string>("BirthYear")
                        .HasColumnType("text");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("FamilyName")
                        .HasColumnType("text");

                    b.Property<long>("MyCompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Passport")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("SurName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("MyCompanyId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("ExportOrderEntites.ReleaseRecord.ReleaseImportContainerRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillOfLadingNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LineName")
                        .HasColumnType("text");

                    b.Property<long>("LockToken")
                        .HasColumnType("bigint");

                    b.Property<int>("ReleaseMode")
                        .HasColumnType("integer");

                    b.Property<int>("ReleaseStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReleaseTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReleaseUID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TerminalErrorResponse")
                        .HasColumnType("text");

                    b.Property<string>("TerminalName")
                        .HasColumnType("text");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("ReleaseContainerRecords", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.ReleaseRecord.ReleaseRemark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillOfLadingNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LockToken")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("ReleaseRemarks", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselCallDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentPOD")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<long?>("FinalDestinationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PODId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long>("VesselCallId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("FinalDestinationId");

                    b.HasIndex("PODId");

                    b.HasIndex("VesselCallId");

                    b.ToTable("VesselCall_Details", (string)null);
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselCallEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ETA")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ETS")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TerminalId")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long>("VesselId")
                        .HasColumnType("bigint");

                    b.Property<string>("VoyageNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoyageNoTerminal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("TerminalId");

                    b.HasIndex("VesselId");

                    b.ToTable("VesselCalls");
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselCallHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ETA")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ETS")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TerminalName")
                        .HasColumnType("text");

                    b.Property<string>("VesselName")
                        .HasColumnType("text");

                    b.Property<string>("VoyageNo")
                        .HasColumnType("text");

                    b.Property<string>("VoyageNoTerminal")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.ToTable("VesselCallHistory");
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CaptainFamily")
                        .HasColumnType("text");

                    b.Property<string>("CaptainName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("FlagId")
                        .HasColumnType("bigint");

                    b.Property<string>("IMO")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TerminalCode")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("FlagId");

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DocumentEntityExportOrderEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.Document.DocumentEntity", null)
                        .WithMany()
                        .HasForeignKey("DocumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExportOrderEntites.ExportOrder.ExportOrderEntity", null)
                        .WithMany()
                        .HasForeignKey("ExportOrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExportOrderEntites.BillofLading.BillofLadingContainerRecord", b =>
                {
                    b.HasOne("ExportOrderEntites.BillofLading.BillofLadingEntity", null)
                        .WithMany("ContainerRecords")
                        .HasForeignKey("BillofLadingEntityId");
                });

            modelBuilder.Entity("ExportOrderEntites.BillofLading.BillofLadingEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.ImportVesselCall.ImportVesselCallDetail", "VesselCallDetail")
                        .WithMany("BillofLadings")
                        .HasForeignKey("VesselCallDetailId");

                    b.Navigation("VesselCallDetail");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CarrierCatalog", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.HasOne("ExportOrderEntites.Catalog.LocationCatalog", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("CreateUser");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CarrierTerminalDetails", b =>
                {
                    b.HasOne("ExportOrderEntites.Catalog.CarrierCatalog", "Carrier")
                        .WithMany("CarrierDetails")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CountryCatalog", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CustomsCatalog", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.LocationCatalog", b =>
                {
                    b.HasOne("ExportOrderEntites.Catalog.CountryCatalog", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("Country");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.SupplementaryUnitCatalog", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.TerminalCatalog", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.HasOne("ExportOrderEntites.Catalog.CustomsCatalog", "Customs")
                        .WithMany()
                        .HasForeignKey("CustomsId");

                    b.HasOne("ExportOrderEntites.Catalog.LocationCatalog", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("CreateUser");

                    b.Navigation("Customs");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.CommodityCatalog", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.CustomerCatalog", b =>
                {
                    b.HasOne("ExportOrderEntites.Catalog.CountryCatalog", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("Country");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.DocumentEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.DocumentHistory", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.DocumentRecord", b =>
                {
                    b.HasOne("ExportOrderEntites.Document.DocumentEntity", "Document")
                        .WithMany("Records")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ContainerContent", b =>
                {
                    b.HasOne("ExportOrderEntites.Document.DocumentRecord", "DocumentRecord")
                        .WithMany()
                        .HasForeignKey("DocumentRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExportOrderEntites.ExportOrder.ExportOrderRecord", "ExportOrderRecord")
                        .WithMany("Contents")
                        .HasForeignKey("ExportOrderRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExportOrderEntites.Catalog.SupplementaryUnitCatalog", "SupplementaryUnit")
                        .WithMany()
                        .HasForeignKey("SupplementaryUnitId");

                    b.Navigation("DocumentRecord");

                    b.Navigation("ExportOrderRecord");

                    b.Navigation("SupplementaryUnit");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.Catalog.CarrierCatalog", "Carrier")
                        .WithMany()
                        .HasForeignKey("CarrierId");

                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.HasOne("ExportOrderEntites.MyCompany.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("ExportOrderEntites.VesselCall.VesselCallDetail", "VesselCallDetail")
                        .WithMany("ExportOrders")
                        .HasForeignKey("VesselCallDetailId");

                    b.Navigation("Carrier");

                    b.Navigation("CreateUser");

                    b.Navigation("Person");

                    b.Navigation("VesselCallDetail");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderHistory", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderRecord", b =>
                {
                    b.HasOne("ExportOrderEntites.Cntr.CntrTpSz", "CntrType")
                        .WithMany()
                        .HasForeignKey("CntrTypeISO");

                    b.HasOne("ExportOrderEntites.ExportOrder.ExportOrderEntity", "ExportOrder")
                        .WithMany("Records")
                        .HasForeignKey("ExportOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CntrType");

                    b.Navigation("ExportOrder");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderRecordHistory", b =>
                {
                    b.HasOne("ExportOrderEntites.ExportOrder.ExportOrderHistory", "ExportOrder")
                        .WithMany("Records")
                        .HasForeignKey("ExportOrderId");

                    b.Navigation("ExportOrder");
                });

            modelBuilder.Entity("ExportOrderEntites.ImportVesselCall.ImportVesselCallDetail", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.HasOne("ExportOrderEntites.Catalog.LocationCatalog", "FinalDestination")
                        .WithMany()
                        .HasForeignKey("FinalDestinationId");

                    b.HasOne("ExportOrderEntites.Catalog.LocationCatalog", "POD")
                        .WithMany()
                        .HasForeignKey("PODId");

                    b.HasOne("ExportOrderEntites.ImportVesselCall.ImportVesselCallEntity", "VesselCall")
                        .WithMany("Details")
                        .HasForeignKey("VesselCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateUser");

                    b.Navigation("FinalDestination");

                    b.Navigation("POD");

                    b.Navigation("VesselCall");
                });

            modelBuilder.Entity("ExportOrderEntites.ImportVesselCall.ImportVesselCallEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.HasOne("ExportOrderEntites.Catalog.TerminalCatalog", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExportOrderEntites.VesselCall.VesselEntity", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateUser");

                    b.Navigation("Terminal");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("ExportOrderEntites.MyCompany.MyCompanyEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.MyCompany.PersonEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.HasOne("ExportOrderEntites.MyCompany.MyCompanyEntity", "MyCompany")
                        .WithMany("Persons")
                        .HasForeignKey("MyCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateUser");

                    b.Navigation("MyCompany");
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselCallDetail", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.HasOne("ExportOrderEntites.Catalog.LocationCatalog", "FinalDestination")
                        .WithMany()
                        .HasForeignKey("FinalDestinationId");

                    b.HasOne("ExportOrderEntites.Catalog.LocationCatalog", "POD")
                        .WithMany()
                        .HasForeignKey("PODId");

                    b.HasOne("ExportOrderEntites.VesselCall.VesselCallEntity", "VesselCall")
                        .WithMany("Details")
                        .HasForeignKey("VesselCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateUser");

                    b.Navigation("FinalDestination");

                    b.Navigation("POD");

                    b.Navigation("VesselCall");
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselCallEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.HasOne("ExportOrderEntites.Catalog.TerminalCatalog", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExportOrderEntites.VesselCall.VesselEntity", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateUser");

                    b.Navigation("Terminal");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselCallHistory", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselEntity", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExportOrderEntites.Catalog.CountryCatalog", "Flag")
                        .WithMany()
                        .HasForeignKey("FlagId");

                    b.Navigation("CreateUser");

                    b.Navigation("Flag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExportOrderEntites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ExportOrderEntites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExportOrderEntites.BillofLading.BillofLadingEntity", b =>
                {
                    b.Navigation("ContainerRecords");
                });

            modelBuilder.Entity("ExportOrderEntites.Catalog.CarrierCatalog", b =>
                {
                    b.Navigation("CarrierDetails");
                });

            modelBuilder.Entity("ExportOrderEntites.Document.DocumentEntity", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderEntity", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderHistory", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("ExportOrderEntites.ExportOrder.ExportOrderRecord", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("ExportOrderEntites.ImportVesselCall.ImportVesselCallDetail", b =>
                {
                    b.Navigation("BillofLadings");
                });

            modelBuilder.Entity("ExportOrderEntites.ImportVesselCall.ImportVesselCallEntity", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("ExportOrderEntites.MyCompany.MyCompanyEntity", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselCallDetail", b =>
                {
                    b.Navigation("ExportOrders");
                });

            modelBuilder.Entity("ExportOrderEntites.VesselCall.VesselCallEntity", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
